### ISSUE TITLE
ios folder is redundant

### ISSUE THREAD

**Issue by fobos531** [Shikhar15606/react-native-accurate-step-counter#2]
Hello,

First of all, I would like to give you my sincerest thanks for sharing this library, it has helped immensely in implementing a pedometer as part of on app I'm working on. Great work!

That said, I believe the ios folder is redundant in this project. If I attempt to install pods in my RN project, the command will fail due to [an error in the podspec file](https://github.com/Shikhar15606/react-native-accurate-step-counter/blob/main/ios/RNWalkCounter.podspec#L9). The homepage entry shouldn't be blank, but since the iOS part of the project is simply a placeholder, I figured it could be deleted altogether.

Let me know what you think regarding this :)

**Comment by Abhishek357** [comment]
Glad to hear that it helped you. We haven't tested for the ios part. We will do it in the future and are also open to contribution :hugs:

**Comment by Shikhar15606** [comment]
Yes, this package is only for android.

**Comment by cgruca** [comment]
Ah ok thanks for letting me know @Shikhar15606. Do you know if there's a good solution out there for ios?
I know react-native-fitness is popular but that only updates steps every minute, while I need something like what you have here that updates constantly. Any help is appreciated, thanks!

**Comment by Shikhar15606** [comment]
@cgruca , I am not aware of the solutions for ios. You can check [this](https://dzone.com/articles/how-to-develop-a-simple-step-counter-app-on-reactn) blog to create one, and I will be grateful if you will make a PR for the same. We are open to contribution 🤗

**Comment by cgruca** [comment]
Hello, I ended up going with a CMPedometer wrapper for ios - the one i used is react-native-pedometer-huangxt.
Then i just check whether the platform is android or ios and use the corresponding package for it.
Not the ideal solution but it's good enough.
