### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by cgtysnpr** [Shikhar15606/react-native-accurate-step-counter#4]
Im getting  "Could not resolve dependency" error when I try to download.

**Comment by Shikhar15606** [comment]
@cgtysnpr Can you give some more info about the problem? You can install our package by the install command given in the readme file of our project.

**Comment by cgtysnpr** [comment]
![install-error](https://user-images.githubusercontent.com/49885578/143584455-55c8ee62-715f-4470-b82a-eff03fdbdf6c.png)
getting this error. But i can install other react native packages
